/******/(function (modules) {
/******/    var installedModules = {};
/******/    function require(moduleId) {
/******/      if (installedModules[moduleId]) {
/******/        return installedModules[moduleId].exports;
/******/      }
/******/
/******/      var module = installedModules[moduleId] = {
/******/       exports: {},
/******/      };
/******/
/******/      console.log("single moduleId = ", moduleId);
/******/
/******/      modules[moduleId](
/******/        module,
/******/        module.exports,
/******/        require,
/******/      ); 
/******/
/******/      return module.exports;
/******/    }
/******/    require.ensure = function(chunkId, callback) {
/******/      callback(require);
/******/    }
/******/    return require(0);
/******/})
({
/*******/0: function(module, exports, require) {

function getTemplate(templateName) {
	return require(/* ./templates */1)("./"+templateName);
}
console.log(getTemplate("a"));
console.log(getTemplate("b"));

/*******/},
/*******/
/*******/1: function(module, exports, require) {

/***/module.exports = function(name) {
/***/	var map = {"./a.js":2,"./c.js":4,"./b.js":3};
/***/ console.log('name = ', name);/***/	var value = require(map[name]|| map[name + ".web.js"]|| map[name + ".js"]);
/***/ console.log('value = ', value);/***/	return value;/***/};

/*******/},
/*******/
/*******/2: function(module, exports, require) {

module.exports = function() {
	return "This text was generated by template A";
}

/*******/},
/*******/
/*******/3: function(module, exports, require) {

module.exports = function() {
	return "This text was generated by template B";
}

/*******/},
/*******/
/*******/4: function(module, exports, require) {

module.exports = function() {
	return "This text was generated by template C";
}

/*******/},
/*******/
/*******/})