/*******/webpackJsonp(1, {
/*******/1: function(module, exports, require) {

/***/module.exports = function(name) {
/***/	var map = {"./a.js":2,"./c.js":3,"./b.js":4};
/***/ console.log('name = ', name);/***/	var value = require(map[name]|| map[name + ".web.js"]|| map[name + ".js"]);
/***/ console.log('value = ', value);/***/	return value;/***/};

/*******/},
/*******/
/*******/2: function(module, exports, require) {

module.exports = function() {
	return "This text was generated by template A";
}

/*******/},
/*******/
/*******/3: function(module, exports, require) {

module.exports = function() {
	return "This text was generated by template C";
}

/*******/},
/*******/
/*******/4: function(module, exports, require) {

module.exports = function() {
	return "This text was generated by template B";
}

/*******/},
/*******/
/*******/})